### ISSUE TITLE
Ubody Dataset

### ISSUE THREAD

**Issue by fatbao55** [IDEA-Research/OSX#2]
Hi authors, thanks for the great work! 

I have a few questions:
1) Is the Ubody dataset used in the training of the experiments in Table 3? 
2) When will the dataset be released? :)

**Comment by linjing7** [comment]
Hi, thanks for your interest in our work. We do not use UBody in the experiments of Table 3. The training set we use in Table 3 are:
(1) Left Column: train on AGORA-train; test on AGORA-test
(2) Middle Column: train on Human3.6m, MSCOCO, MPII; test on EHF
(3) Right Column: train on Human3.6m, MSCOCO, MPII, mpi_inf_3dhp, 3DPW-train; test on 3DPW-test.
We plan to release UBody by about 15, April.

**Comment by fatbao55** [comment]
@linjing7 Thanks for the clarification! Have you tried training with UBody dataset for experiments in Table 3? I was wondering if it could be helpful as an additional train dataset.

Looking forward to the dataset release!

**Comment by linjing7** [comment]
Hi, since the existing datasets are captured in simulated or laboratory environments, while UBody concentrates on real-life scenes, their distributions of them are quite different. Thus, I think UBody would not significantly improve the performance in these two datasets. I would do this performance in the future.

**Comment by fatbao55** [comment]
I see, thanks for clarifying!

**Comment by fatbao55** [comment]
Is there any update on the dataset? :)
