### ISSUE TITLE
Gender for AGORA not used

### ISSUE THREAD

**Issue by fabienbaradel** [IDEA-Research/OSX#53]
Hi,
Congrats for your work and thanks for releasing your code.
The SMPLX annotations for AGORA contain the ```gender``` that you are preprocessing [here](https://github.com/IDEA-Research/OSX/blob/main/tool/AGORA/agora2coco.py#L137) however it seems that in your [dataloader](https://github.com/IDEA-Research/OSX/blob/main/data/AGORA/AGORA.py) you are not using the gender. And you are using the shape while the shape is male/female dependant.
Could you explain if we can just throw away the ```gender``` like you are doing? Otherwise I think that I am missing something.
Thanks in advance for you answer,

**Comment by linjing7** [comment]
Hi, thanks for your interest. In fact, specifying the `gender` label and select the corresponding SMPLX model will be beneficial to the reconstruction. However, our model could not  estimate the `gender` of a person given an RGB image. Thus, we use the 'neutral' gender in our [model](https://github.com/IDEA-Research/OSX/blob/07f1b0212cf1e84a361957b12a3ffe56f7476210/main/OSX.py#L37).  To keep consistent, we do not use the gender label in the `dataloader`, either.  I think you can try to estimate the `gender` label and choose to use the corresponding SMPLX model, which will improve the performance. But throwing away the `gender` will would not lead to severe degradation since the major bottleneck in this task is the pose estimation.

**Comment by fabienbaradel** [comment]
Thanks a lot @linjing7 for your answer :) It makes a lot of sense.
My main concern is about the ```shape```. The ```shape``` is **gender-specific** in SMPLX as far as I know so when you are using a ```neutral``` model it does not corresponds to the ground-truth ``` shape```. Did you encounter any issue related to this topic?

**Comment by linjing7** [comment]
Hi, you are right. The `shape` is gender-specific in SMPLX. I do not encounter severe `shape` problem in AGORA-test as shown [here](https://osx-ubody.github.io/). I think you can have a try on the `AGORA-val `dataset to verify whether the `gender` label will bring a significant difference, since the `gender` label is available in the valiation set so we can directly use it in the [model](https://github.com/IDEA-Research/OSX/blob/07f1b0212cf1e84a361957b12a3ffe56f7476210/main/OSX.py#L37).
