### ISSUE TITLE
The Problem of Mesh Coordinate Values

### ISSUE THREAD

**Issue by LiuShiyu95** [IDEA-Research/OSX#64]
I use SMPL model or HMR model to generate mesh coordinates that are close to 0, while the z-coordinate values of the mesh generated using OSX are very large. Is it related to the setting of camera parameters, and is there a conversion between mesh?

**Comment by linjing7** [comment]
Hi, this is because we have added the camera translation on the vertices:
https://github.com/IDEA-Research/OSX/blob/13df1cbf9cc5ae72deb46ce7ab5832e7bcb8bd9d/main/OSX.py#L93
You can save the original vertices before adding the trans and the z-coordinate values should be also close to 0:
https://github.com/IDEA-Research/OSX/blob/13df1cbf9cc5ae72deb46ce7ab5832e7bcb8bd9d/main/OSX.py#L68C24-L68C24

**Comment by LiuShiyu95** [comment]
> 

Thank you for your reply! I have solved the problem according to your method.
