### ISSUE TITLE
Unable to inference on 32GB V100

### ISSUE THREAD

**Issue by alvinliu0** [IDEA-Research/OSX#7]
Hi:)

When I try to run the demo.py code, I get the CUDA out of memory bug on 32GB V100. Just to make sure whether it's my implementation error, or that it's unable to inference with 32GB memory?

Many thx

**Comment by linjing7** [comment]
Hi, I succeed in running the demo in 24G RTX3090. I think there is something wrong with you. Which versions of Pytorch and CUDA do you use? Besides, you can add "CUDA_VISIBLE_DEVICES=xxx" to specify which GPU to be used.

**Comment by alvinliu0** [comment]
Hi:)

Thanks for your prompt reply! I use the environment exactly as you recommend, i.e., CUDA 11.3, torch 1.11.0, mmcv 1.7.1. Besides, I do not make any modification to the code and use the input.png you provide. It's seems quite weird. Could it due to the "If you run this code in ssh environment without display device" issues? I'm running inference on a slurm cluster and do not specifically deal with this step.

Many thanks!

**Comment by linjing7** [comment]
Hi:)
It's quite weird. I test on RTX3090 and the used memory is about 10G. Could you please test on an RTX3090 to check whether it is caused by the hardware? I'm sorry that I'm unable to test on a V100.
<img width="860" alt="image" src="https://user-images.githubusercontent.com/70081899/230340999-572154de-3e83-4b51-b4d0-b70919234b79.png">
BTW, which line raises this bug, is `out = model(inputs, targets, meta_info, 'test')`?

**Comment by linjing7** [comment]
@alvinliu0 Hi, if you have not solved the problem yet, you can add my WeChat `15625292431`. I think it would be more efficient and let's solve the problem together to make the repo better :)

**Comment by alvinliu0** [comment]
Great! Thx bro!
